---
title: "Murphy Data Cleaning"
author: "Stella BooydeGraaff"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE, echo=FALSE}

knitr::opts_chunk$set(eval = TRUE, echo = FALSE, warning = FALSE, fig.width = 7, fig.height = 6)

library(tidyverse)
library(wesanderson)
```

```{r}
data <- read_csv("data/Murphy_Appendix_all_data.csv") 

head(data)
```

```{r} 
data <- data |>
  select(-file) 

head(data)
```

```{r}
  data <- data %>%
      mutate(
          # Check if 'proportion' is in the variable_detailed
          is_proportion = grepl("proportion", variable_detailed, ignore.case = TRUE),
          
          # Create value_type based on the presence of 'proportion'
          value_type = ifelse(is_proportion, 
                              "proportion", 
                              "number"),
          
          # Remove 'proportion' text from variable_detailed
          variable_detailed = ifelse(is_proportion, gsub("proportion", "", variable_detailed, ignore.case = TRUE), variable_detailed),
          
          # Trim whitespace
          variable_detailed = trimws(variable_detailed),
          
          # cleaned variable_detailed to numeric
          variable_detailed_numeric = suppressWarnings(as.numeric(variable_detailed)),
          
          # Update value_type to "number" if variable_detailed_numeric is greater than 1
          value_type = ifelse(!is.na(variable_detailed_numeric) & variable_detailed_numeric > 1, 
                              "number", 
                              value_type)
      ) %>%
      # Drop temporary columns
      select(-is_proportion, -variable_detailed_numeric)

```

```{r}
data <- data %>%
    rename(variable_type = variatble_type)

```

```{r}
#race
data <- data %>%
  mutate(
    variable_detailed = case_when(
      variable_type == "race" & grepl("\\basian\\b", variable_detailed, ignore.case = TRUE) ~ "asian_total",
      variable_type == "race" & grepl("\\bblack\\b", variable_detailed, ignore.case = TRUE) ~ "black_total",
      variable_type == "race" & grepl("\\bafrican_american\\b", variable_detailed, ignore.case = TRUE) ~ "black_total",
      variable_type == "race" & grepl("\\bblack_\\b", variable_detailed, ignore.case = TRUE) ~ "black_total",
      variable_type == "race" & grepl("\\bhispanic\\b", variable_detailed, ignore.case = TRUE) ~ "hispanic_total",
      variable_type == "race" & grepl("\\bhispanic_\\b", variable_detailed, ignore.case = TRUE) ~ "hispanic_total",
      variable_type == "race" & grepl("\\bnative\\b", variable_detailed, ignore.case = TRUE) ~ "native_american_total",
      variable_type == "race" & grepl("\\bamerican_indian\\b", variable_detailed, ignore.case = TRUE) ~ "native_american_total",
       variable_type == "race" & grepl("\\bnative_american\\b", variable_detailed, ignore.case = TRUE) ~ "native_american_total",
      variable_type == "race" & grepl("\\bwhite\\b", variable_detailed, ignore.case = TRUE) ~ "white_total",
      variable_type == "race" & grepl("\\bcausasian\\b", variable_detailed, ignore.case = TRUE) ~ "white_total",
      variable_type == "race" & grepl("\\bcaucasian\\b", variable_detailed, ignore.case = TRUE) ~ "white_total",
      variable_type == "race" & grepl("\\bcausasian_\\b", variable_detailed, ignore.case = TRUE) ~ "white_total",
      variable_type == "race" & grepl("\\bother\\b", variable_detailed, ignore.case = TRUE) ~ "other_total",
      variable_type == "race" & grepl("\\basian_offender\\b", variable_detailed, ignore.case = TRUE) ~ "asian_convicted_offender",
      variable_type == "race" & grepl("\\bblack_offender\\b", variable_detailed, ignore.case = TRUE) ~ "black_convicted_offender",
      variable_type == "race" & grepl("\\bhispanic_offender\\b", variable_detailed, ignore.case = TRUE) ~ "hispanic_convicted_offender",
      variable_type == "race" & grepl("\\bnative_american_offender\\b", variable_detailed, ignore.case = TRUE) ~ "native_american_convicted_offender",
      variable_type == "race" & grepl("\\bwhite_offender\\b", variable_detailed, ignore.case = TRUE) ~ "white_convicted_offender",
      variable_type == "race" & grepl("\\bcaucasian_offender\\b", variable_detailed, ignore.case = TRUE) ~ "white_convicted_offender",
      variable_type == "race" & grepl("\\bcaucasian_convicted_offender\\b", variable_detailed, ignore.case = TRUE) ~ "white_convicted_offender",
      variable_type == "race" & grepl("\\bother_offender\\b", variable_detailed, ignore.case = TRUE) ~ "other_convicted_offender",
      variable_type == "race" & grepl("\\bafrican_american__convicted_offender\\b", variable_detailed, ignore.case = TRUE) ~ "black_convicted_offender",
      variable_type == "race" & grepl("\\bafrican_american_convicted_offender\\b", variable_detailed, ignore.case = TRUE) ~ "black_convicted_offender",
      variable_type == "race" & grepl("\\bafrican_american_offender\\b", variable_detailed, ignore.case = TRUE) ~ "black_convicted_offender",
      variable_type == "race" & grepl("\\bafrican_american_arrestee\\b", variable_detailed, ignore.case = TRUE) ~ "black_arrestee",
      variable_type == "race" & grepl("\\bcaucasian_arrestee\\b", variable_detailed, ignore.case = TRUE) ~ "white_arrestee",
      TRUE ~ variable_detailed
    ))
    
#DNA collection breakdown
data <- data %>%
  mutate(
    variable_detailed = case_when(
      variable_type == "DNA_collection_breakdown" & grepl("asian", variable_detailed, ignore.case = TRUE) ~ "asian_annual",
      variable_type == "DNA_collection_breakdown" & grepl("black", variable_detailed, ignore.case = TRUE) ~ "black_annual",
      variable_type == "DNA_collection_breakdown" & grepl("hispanic", variable_detailed, ignore.case = TRUE) ~ "hispanic_annual",
      variable_type == "DNA_collection_breakdown" & grepl("native", variable_detailed, ignore.case = TRUE) ~ "native_american_annual",
      variable_type == "DNA_collection_breakdown" & grepl("white", variable_detailed, ignore.case = TRUE) ~ "white_annual",
      variable_type == "DNA_collection_breakdown" & grepl("other", variable_detailed, ignore.case = TRUE) ~ "other_annual",
      TRUE ~ variable_detailed
    )
  )
    
```

```{r}
# Update 'variable_type' to 'race' where it is 'DNA_collection_breakdown'

data <- data %>%
  mutate(
    variable_type = ifelse(variable_type == "DNA_collection_breakdown", "race", variable_type))
```

```{r}
#state demographic
data <- data %>%
  mutate(
    variable_detailed = case_when(
      variable_type == "state_demographic" & grepl("asian", variable_detailed, ignore.case = TRUE) ~ "asian_state",
      variable_type == "state_demographic" & grepl("black", variable_detailed, ignore.case = TRUE) ~ "black_state",
      variable_type == "state_demographic" & grepl("hispanic", variable_detailed, ignore.case = TRUE) ~ "hispanic_state",
      variable_type == "state_demographic" & grepl("native", variable_detailed, ignore.case = TRUE) ~ "native_american_state",
      variable_type == "state_demographic" & grepl("white", variable_detailed, ignore.case = TRUE) ~ "white_state",
      variable_type == "state_demographic" & grepl("other", variable_detailed, ignore.case = TRUE) ~ "other_state",
      TRUE ~ variable_detailed
    )
  )

```

```{r}
# Update 'variable_type' to 'race' where it is 'state_demographic'

data <- data %>%
  mutate(
    variable_type = ifelse(variable_type == "state_demographic", "race", variable_type))
```

```{r}
#population data collected variables
data <- data %>%
  mutate(
    variable_detailed = case_when(
      variable_type == "population_data_collected" & grepl("asian", variable_detailed, ignore.case = TRUE) ~ "asian_pop_collected",
      variable_type == "population_data_collected" & grepl("black", variable_detailed, ignore.case = TRUE) ~ "black_pop_collected",
      variable_type == "population_data_collected" & grepl("hispanic", variable_detailed, ignore.case = TRUE) ~ "hispanic_pop_collected",
      variable_type == "population_data_collected" & grepl("native", variable_detailed, ignore.case = TRUE) ~ "native_american_pop_collected",
      variable_type == "population_data_collected" & grepl("white", variable_detailed, ignore.case = TRUE) ~ "white_pop_collected",
      variable_type == "population_data_collected" & grepl("other", variable_detailed, ignore.case = TRUE) ~ "other_pop_collected",
      TRUE ~ variable_detailed
    )
  )
```

```{r}
# Update 'variable_type' to 'race' where it is 'population_data_collected'

data <- data %>%
  mutate(
    variable_type = ifelse(variable_type == "population_data_collected", "race", variable_type))
```

```{r}
#sex variable type
data <- data %>%
  mutate(
    variable_detailed = case_when(
      variable_type == "sex" & grepl("\\bfemale\\b", variable_detailed, ignore.case = TRUE) ~ "female_total",
      variable_type == "sex" & grepl("\\bfemale_\\b", variable_detailed, ignore.case = TRUE) ~ "female_total",
      variable_type == "sex" & grepl("\\bfemales\\b", variable_detailed, ignore.case = TRUE) ~ "female_total",
      variable_type == "sex" & grepl("\\bfemale_offender\\b", variable_detailed, ignore.case = TRUE) ~ "female_convicted_offender",
      variable_type == "sex" & grepl("\\bmale\\b", variable_detailed, ignore.case = TRUE) ~ "male_total",
      variable_type == "sex" & grepl("\\bmale_\\b", variable_detailed, ignore.case = TRUE) ~ "male_total",
      variable_type == "sex" & grepl("\\bmales\\b", variable_detailed, ignore.case = TRUE) ~ "male_total",
      TRUE ~ variable_detailed 
    )
  )
```

```{r}
data <- data %>%
  mutate(
    variable_type = ifelse(variable_type == "gender", "sex", variable_type))
```

```{r}
data <- data %>%
  mutate(
    variable_detailed = case_when(
      variable_type == "offender_type" & grepl("\\barrestee\\b", variable_detailed, ignore.case = TRUE) ~ "arrestee_total",
      variable_type == "offender_type" & grepl("\\barrested_offender\\b", variable_detailed, ignore.case = TRUE) ~ "arrestee_total",
      variable_type == "offender_type" & grepl("\\bconvicted_offender\\b", variable_detailed, ignore.case = TRUE) ~ "convicted_offender_total",
      variable_type == "offender_type" & grepl("\\bconviceted_offender\\b", variable_detailed, ignore.case = TRUE) ~ "convicted_offender_total",
      variable_type == "offender_type" & grepl("\\boffender\\b", variable_detailed, ignore.case = TRUE) ~ "convicted_offender_total",
      TRUE ~ variable_detailed 
    )
  )
```

```{r}
write.csv(data, "data/murphy_foia_cleaned.csv")
```


```{r}
#data visualizations
data_gender <- data |> 
  filter(variable_type == "sex")


california_totals <- data_gender |> 
  filter(State == "California") |> 
  summarise(
    male_total = sum(value[grepl("male", variable_detailed, ignore.case = TRUE)]),
    female_total = sum(value[grepl("female", variable_detailed, ignore.case = TRUE)]),
    unknown_total = sum(value[grepl("unknown", variable_detailed, ignore.case = TRUE)])
  ) 
```


```{r}
california_totals <- california_totals |>  
  pivot_longer(cols = everything(), names_to = "variable_detailed", values_to = "value")|> 
  mutate(
    State = "California",
    variable_type = "sex",
    value_type = "proportion"
  )
```

```{r}
#create a dataset with gender values as proportions only
data_gender_proportions <- data_gender  |> 
  group_by(State, variable_type, value_type) |>   # Group by relevant columns
  mutate(proportion = value / sum(value)) |>      # Calculate proportion
  ungroup() |>                                    # Ungroup to prevent grouping in the output
  select(-value, -value_type)|>                   # remove the value and value_type columns
  rename(proportion_value = proportion)           # Rename the new proportion column


data_gender_simplified <- data_gender_proportions |> 
  mutate(
 simplified_sex = case_when(
      str_detect(variable_detailed, "\\bmale\\b") ~ "male",
      str_detect(variable_detailed, "\\bmale_total\\b") ~ "male",
      str_detect(variable_detailed, "\\bmale_convicted_offender\\b") ~ "male",
      str_detect(variable_detailed, "\\bmale_arrestee\\b") ~ "male",
      str_detect(variable_detailed, "\\bfemale_total\\b") ~ "female",
      str_detect(variable_detailed, "\\bfemale_convicted_offender\\b") ~ "female",
      str_detect(variable_detailed, "\\bfemale_offender\\b") ~ "female",
      str_detect(variable_detailed, "\\bfemale_arrestee\\b") ~ "female",
      str_detect(variable_detailed, "\\bfemale\\b") ~ "female",
      TRUE ~ "unknown"
    )
  ) |> 
  group_by(State, simplified_sex) |> 
  summarize(total_value = sum(proportion_value), .groups = 'drop')

#stacked bar chart simplified
ggplot(data_gender_simplified, aes(x = State, y = total_value, fill = simplified_sex)) +
  geom_bar(stat = "identity") +  # Stacked bar chart by default
  scale_fill_manual(values = c("#489C92", "#F38C79", "#D8DCDA")) +  # color palette
  labs(y = "Proportion", x = "State", title = "NDIS Gender Distribution by State", fill = "Sex") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
#create data set with variable_type "race"
data_race <- data |> 
  filter(variable_type == "race")

#create a data set with totals combining "convicted_offender" and "arrestee" data into totals by race
convicted_arrestee_totals <- data_race |> 
  filter(str_detect(variable_detailed, "_convicted_offender|_arrestee")) |> 
  mutate(variable_detailed = str_replace(variable_detailed, "_convicted_offender|_arrestee", "_total")) |> 
  group_by(State, variable_detailed) |> 
  summarize(value = sum(value), .groups = 'drop') |>
  mutate(value_type = "number")

# Combine and process race_totals
race_totals <- data_race |> 
  mutate(variable_detailed = case_when(
    str_detect(variable_detailed, "other_total|unknown") ~ "other_or_unknown",
    TRUE ~ variable_detailed
  )) |> 
  filter(str_detect(variable_detailed, "_total") | str_detect(variable_detailed, "other_or_unknown"))

# Add convicted_arrestee_totals to race_totals
race_totals <- race_totals |> 
  bind_rows(convicted_arrestee_totals) |> 
  group_by(State, variable_detailed) |> 
  summarize(value = sum(value), value_type = first(value_type), .groups = 'drop') |> 
  ungroup()

# Calculate the proportion value within each state
race_totals <- race_totals |> 
  group_by(State) |> 
  mutate(proportion_value = ifelse(value_type == "number", value / sum(value), NA)) |> 
  ungroup()

#keep already calculated proportions and remove value_type column
race_totals <- race_totals |> 
  mutate(proportion_value = ifelse(is.na(proportion_value), value, proportion_value)) |> 
  select(-value_type)

# Replace race category names for clarity
race_totals <- race_totals |> 
  mutate(variable_detailed = case_when(
    variable_detailed == "white_total" ~ "White",
    variable_detailed == "black_total" ~ "Black or African American",
    variable_detailed == "asian_total" ~ "Asian",
    variable_detailed == "hispanic_total" ~ "Hispanic",
    variable_detailed == "native_american_total" ~ "Native American",
    variable_detailed == "other_total" ~ "Other or Unknown",
    variable_detailed == "other_or_unknown" ~ "Other or Unknown",
    TRUE ~ variable_detailed
  ))

# Set the desired order for race categories
desired_order <- c("Other or Unknown", "Native American", "Hispanic", "Asian", "Black or African American", "White")

# Create the bar plot
ggplot(race_totals |> 
       mutate(variable_detailed = factor(variable_detailed, levels = desired_order)),
       aes(x = State, y = proportion_value, fill = variable_detailed)) +
  geom_bar(stat = "identity") + 
  labs(title = "NDIS Race Totals by State",
       x = "State",
       y = "Proportion",
       fill = "Race Category") +
  scale_fill_manual(values = c("#BAD1DC", "#489C92","#59B8B2", "#91C8D0", "#05686D", "#F38C79")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

For most states, the percentage of non-White people whose DNA is collected annually is greater than that of White people. This is most evident for the Black population, which consistently showed the greatest levels of disparity.
```{r}
#Graph showing stats of percent of population 

data_pop_collected <- data_race |> 
  filter(str_detect(variable_detailed, "_pop_collected")) |> 
  mutate(race_category = case_when(
    str_detect(variable_detailed, "black") ~ "Black",
    str_detect(variable_detailed, "white") ~ "White",
    TRUE ~ "Other"
  )) |> 
    group_by(State, race_category) |> 
  summarise(total_value = sum(value, na.rm = TRUE))

ggplot(data_pop_collected, aes(x ="", y = total_value, fill = race_category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y") +
  theme_void() +
  labs(title = "Percentage of Each Race with DNA Collected Annually",
       fill = "Race") +
  scale_fill_manual(values = c("#05686D", "#BAD1DC", "#F38C79"))

summary_pop_collected <- data_pop_collected %>%
  group_by(race_category) %>%
  summarise(avg_pop_collected = mean(total_value, na.rm = TRUE))

# Print the result
print(summary_pop_collected)

```


```{r}
data_offender_type <- data |> 
  filter(variable_type == "offender_type")


#pie chart of offender type

palette <- wes_palette("GrandBudapest2", 3, type = "discrete")

# Rename the offender types
data_offender_type_renamed <- data_offender_type |> 
  mutate(variable_detailed = case_when(
    variable_detailed == "arrestee_total" ~ "Arrestee",
    variable_detailed == "convicted_offender_total" ~ "Convicted Offender",
    TRUE ~ variable_detailed
  ))

# Filter and group by offender type, then summarize
data_offender_type_summarized <- data_offender_type_renamed |> 
  filter(variable_detailed %in% c("Arrestee", "Convicted Offender")) |> 
  group_by(variable_detailed) |> 
  summarize(total_value = sum(value, na.rm = TRUE))

# Calculate total sum of the summarized data
full_value <- sum(data_offender_type_summarized$total_value, na.rm = TRUE)

# Calculate percentages and create labels
data_offender_type_summarized <- data_offender_type_summarized |> 
  mutate(percentage = total_value / full_value * 100,
         label = paste0(round(percentage, 1), "%"))

# Create the pie chart
ggplot(data_offender_type_summarized, aes(x = "", y = total_value, fill = variable_detailed)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y") +  # Converts bar chart to pie chart
  labs(title = "NDIS Distribution of Offender Types", caption = "Data from California, Indiana, Texas, and Nevada", fill = "Offender Type") +
  geom_text(aes(label = label), position = position_stack(vjust = 0.5)) +
  theme_minimal() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank()) +
  scale_fill_manual(values = palette)

```

```{r}


```


