---
title: "Regression to predict CODIS database proportions"
output: html_document
date: "2024-04-28"
site: workflowr::wflow_site
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data, results = FALSE,warning=FALSE,message=FALSE}
# Load necessary libraries
library(readr)        # read csv files
library(tidyverse)    # census API
library(knitr)        
library(jtools) 
library(sandwich)     # robust covariance estimator
library(ggplot2)      # For plotting
library(stats)        # For statistical functions
library(tidycensus)   # For accessing US census data
# Load additional libraries for combining plots
library(cowplot)
library(ggpubr) 
library(viridis)
library(sf)

# Load prison data
prison_data = read.csv("./data/populations_states.csv")

# Load CODIS data
codis_data = read.csv("./data/CODIS_data.csv")

# Create a data frame for Murphy and Tong profiles
murphy.tong = data.frame(
  state = c("California", "Florida", "Indiana", "Maine", "Nevada", "South Dakota", "Texas"), 
  total = c(2768269, 1350667, 307714, 32847, 167726, 67600, 960985,2768269, 1350667, 307714, 32847, 167726, 67600, 960985),
  mt.percent = c(0.296, 0.614, 0.7, 0.928, 0.694, 0.668, 0.373,0.171, 0.352, 0.26, 0.039, 0.256, 0.06, 0.291),
  race = c("White","White","White","White","White","White","White","Black","Black","Black","Black","Black","Black","Black")
)
```

```{r data_wrangling, results = FALSE,warning=FALSE,message=FALSE}
# Load necessary libraries

# Calculate the number of White and Black profiles in Murphy and Tong data
murphy.tong$n = murphy.tong$total * murphy.tong$mt.percent

# Extract year from the date and filter data for 2022
prison_data$year = substring(prison_data$date, 1, 4)
prison_data_2022 = prison_data[which(prison_data$year == "2022"),]
prison_data_2022 = prison_data_2022[!duplicated(prison_data_2022[, 'state']),]

# Load census data for each state
# P1_002N is the total population, P1_003N is the total White population, and P1_004N is the total Black population
us_state_density <- get_decennial(
  geography = "state",
  variables = c(all = "P1_002N", white = "P1_003N", black = "P1_004N"),
  year = 2020,
  geometry = TRUE,
  keep_geo_vars = TRUE
)

# Spread the data into a wider format
us_state_density = spread(us_state_density, variable, value)

# Calculate the proportion of Black and White populations
us_state_density$census.percent.black = us_state_density$black / us_state_density$all
us_state_density$census.percent.white = us_state_density$white / us_state_density$all

# Rename column for merging
us_state_density$state = us_state_density$NAME.x

# Merge census data with prison data
us_state_density = merge(us_state_density, prison_data_2022, by = "state")

# Calculate the proportion of Black and White incarcerated individuals
us_state_density$percent.black.incarc = us_state_density$incarcerated_black / us_state_density$incarcerated_total
us_state_density$percent.white.incarc = us_state_density$incarcerated_white / us_state_density$incarcerated_total

# Merge with CODIS data
us_state_density = merge(us_state_density, codis_data, by = "state")

# Calculate the number of Black and White profiles in CODIS
us_state_density$black_profiles = us_state_density$percent.black.incarc * (us_state_density$offender_profiles)
us_state_density$white_profiles = us_state_density$percent.white.incarc * (us_state_density$offender_profiles)

us_state_density_black = as.data.frame(us_state_density[,c("state","all","black","census.percent.black","incarcerated_total",
                                       "incarcerated_black","percent.black.incarc","arrestee_profiles","offender_profiles","black_profiles")])
us_state_density_black$race = "Black"
colnames(us_state_density_black) = c("state","all","population","census.percent","incarcerated_total",
                                     "incarcerated_race","percent.incar","arrestee_profiles","offender_profiles","geometry","race_profiles","race")

us_state_density_white = as.data.frame(us_state_density[,c("state","all","white","census.percent.white","incarcerated_total",
                                             "incarcerated_white","percent.white.incarc", "arrestee_profiles","offender_profiles","white_profiles")])
us_state_density_white$race = "White"
colnames(us_state_density_white) = c("state","all","population","census.percent","incarcerated_total",
                                     "incarcerated_race","percent.incar","arrestee_profiles","offender_profiles","geometry","race_profiles","race")

inferred_data = rbind(us_state_density_black, us_state_density_white)

# Combine Murphy and Tong data with the merged dataset
combined = merge(murphy.tong, inferred_data, by = c("state","race"), all.x = TRUE)
combined$race_bin = ifelse(combined$race == "White",0,1)

```
```{r proportion_regression, results = FALSE,warning=FALSE,message=FALSE}
# Fit linear models for Black and White population proportions
model.all <- lm(
    mt.percent ~           # Outcome: Murphy & Tong numbers for 7 states
    census.percent +       # Main effect of census proportion on CODIS proportion
    percent.incar +        # Main effect of prison proportion on CODIS proportion
    race_bin+                 # Main effect of race. This will estimate the change in CODIS proportion for different races relative to a baseline race.
    race_bin:census.percent +  # Interaction between race and census proportion.
                           # This checks if the effect of census proportion on CODIS proportion varies by race.
    race_bin:percent.incar,    # Interaction between race and prison proportion.
                           # This checks if the effect of prison proportion on CODIS proportion varies by race.
    data = combined        # The data set containing the variables
)

summary(model.all)
plot_summs(model.all, robust = TRUE)

# Run regression model for different combinations of the following predictors:
# race, census proportion of race, estimated population from Klein data
formula_a = "census.percent + percent.incar + race_bin" # no interactions
formula_b = "percent.incar + race_bin + race_bin:percent.incar" # no census
formula_c = "percent.incar + race_bin"  # no census or interaction
formula_d = "census.percent + percent.incar" # no race

formulas = c(formula_a, formula_b, formula_c, formula_d)

model_df = as.data.frame(matrix(0,nrow = 4, ncol = 3))
colnames(model_df) = c("model","R^2","Anova")
for(i in 1:4){
  form = formulas[[i]]
  model <- lm(paste0('mt.percent ~', form), data = combined)
  p.val = round(anova(model, model.all)[[6]][2],2)
  model_df[i,] = c(form, round(summary(model)$adj.r.squared,2),p.val)
}
kable(model_df)

# generate predictions based on the model with all coefficients
combined$prediction = predict(model.all, combined)

```

```{r plots, results = FALSE,warning=FALSE,message=FALSE}
# Plot the results with linear regression lines
ggplot(data = combined) +
  geom_point(aes(x = prediction, y = mt.percent,fill=state,shape = race),size=5,col="black") +
  scale_shape_manual(name="Race",labels = c("Black","White"),values = c(21,24)) +
  geom_abline(intercept = 0, slope = 1,col ="grey30", linetype = "dashed",size=1.5) +
  theme_classic() + xlab("Estimated CODIS profiles") + ylab("Murphy & Tong profiles (FOIA)") +
  annotate("text", x=0.2, y=0.75, size = 6, label= paste0(as.expression("R² = "), round(summary(model)$adj.r.squared,2))) +
  annotate("text", x=0.6, y=0.56, size = 4, label= "Perfect prediction line",angle = 46) +
  guides(fill=guide_legend(override.aes=list(shape=21))) +
  theme(axis.text.x = element_text(color = "black", size = 16, angle = 0, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(color = "black", size = 16, angle = 0, hjust = 1, vjust = 0, face = "plain"),  
        axis.title.x = element_text(color = "black", size = 16, angle = 0, hjust = .5, vjust = 0, face = "plain"),
        axis.title.y = element_text(color = "black", size = 16, angle = 90, hjust = .5, vjust = .5, face = "plain"),
        aspect.ratio=1) 

combined$Dif <- combined$prediction - combined$mt.percent
combined$Avg <- (combined$prediction + combined$mt.percent) / 2

ggplot(combined, aes(x = Avg, y = Dif)) +
  geom_point(aes(shape = race,fill=state),size=4,col="black") +
  scale_fill_discrete(name = "State") +
  guides(fill=guide_legend(override.aes=list(shape=21))) +
  scale_shape_manual(name="Race",labels = c("Black","White"),values = c(21,24)) +
  geom_hline(yintercept = mean(combined$Dif), colour = "black", size = 1) +
  geom_hline(yintercept = mean(combined$Dif) - (1.96 * sd(combined$Dif)), colour = "grey30", size = 0.5) +
  geom_hline(yintercept = mean(combined$Dif) + (1.96 * sd(combined$Dif)), colour = "grey30", size = 0.5) +
  ylab("Difference Between Measures") +
  xlab("Average Measure") + theme_light() +
  theme(axis.text.x = element_text(color = "black", size = 16, angle = 0, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(color = "black", size = 16, angle = 0, hjust = 1, vjust = 0, face = "plain"),  
        axis.title.x = element_text(color = "black", size = 16, angle = 0, hjust = .5, vjust = 0, face = "plain"),
        axis.title.y = element_text(color = "black", size = 16, angle = 90, hjust = .5, vjust = .5, face = "plain"),
        aspect.ratio=1) 
```
```{r SDIS_regression, results = FALSE,warning=FALSE,message=FALSE,out.width="100%"}
# Read in CSV files
NDIS = read.csv("./data/NDIS.csv")       # National DNA Index System data
SDIS = read.csv("./data/SDIS.csv")       # State DNA Index System data

# Merge NDIS and SDIS datasets by state
NDIS_SDIS = merge(NDIS, SDIS, by = "State")

# Rename columns to distinguish between NDIS and SDIS data
colnames(NDIS_SDIS) <- gsub('.x','.NDIS', names(NDIS_SDIS))
colnames(NDIS_SDIS) <- gsub('.y','.SDIS', names(NDIS_SDIS))

# Merge NDIS_SDIS data with prison data
colnames(prison_data_2022)[12] = "State"
SDIS_states = merge(NDIS_SDIS, prison_data_2022, by = "State")

# Merge census data with NDIS_SDIS_prison data
colnames(us_state_density)[1] = "State"
us_state_population= us_state_density[, c("State", "census.percent.black", "census.percent.white")]
SDIS_regression = merge(SDIS_states, us_state_population, by = "State")

# calculate percent of prison population
SDIS_regression$percent.black.prison = SDIS_regression$incarcerated_black / SDIS_regression$incarcerated_total
SDIS_regression$percent.white.prison = SDIS_regression$incarcerated_white / SDIS_regression$incarcerated_total

# Calculate CODIS black and white proportions using previous regression
SDIS_regression$CODIS.black = model.all$coeff[1] + model.all$coeff[2] * SDIS_regression$census.percent.black + model.all$coeff[3] * SDIS_regression$percent.black.prison + model.all$coeff[4] + model.all$coeff[5]* SDIS_regression$census.percent.black + model.all$coeff[6] * SDIS_regression$percent.black

SDIS_regression$CODIS.white = model.all$coeff[1] + model.all$coeff[2] * SDIS_regression$census.percent.white + model.all$coeff[3] * SDIS_regression$percent.white.prison

SDIS_regression$source = "Regression"
SDIS_regression.trim = SDIS_regression[, c("State", "CODIS.black", "CODIS.white", "source")]

# Prepare data for regression analysis for SDIS arrestees
SDIS_arrestees = SDIS_regression[-c(which(is.na(SDIS_regression$N_arrestees.SDIS))),]
SDIS_arrestees = SDIS_arrestees[, c("State", "N_arrestees.SDIS", "census.percent.black", "census.percent.white", "percent.black.prison", "percent.white.prison", "N_arrestees.NDIS")]

# Linear model for SDIS arrestees using census percent, prison percent, and number of people in NDIS as predictors
SDIS_arrestee = lm(N_arrestees.SDIS ~ census.percent.black + census.percent.white + percent.black.prison + percent.white.prison + N_arrestees.NDIS, data = SDIS_arrestees)
summary(SDIS_arrestee)

# Prepare data for regression analysis for SDIS offenders
SDIS_offenders = SDIS_regression[-c(which(is.na(SDIS_regression$N_offenders.SDIS))),]
SDIS_offenders = SDIS_offenders[, c("State", "N_offenders.SDIS", "census.percent.black", "census.percent.white", "percent.black.prison", "percent.white.prison", "N_offenders.NDIS")]

# Perform regression analysis for SDIS offenders
SDIS_offender = lm(N_offenders.SDIS ~ census.percent.black + census.percent.white + percent.black.prison + percent.white.prison + N_offenders.NDIS, data = SDIS_offenders)
summary(SDIS_offender)

# calculate regression prediction for each state
SDIS_regression$SDIS.arrestee.prediction = SDIS_arrestee$coeff[1] + SDIS_arrestee$coeff[2] * SDIS_regression$census.percent.black +
                                                             SDIS_arrestee$coeff[3] * SDIS_regression$census.percent.white +
                                                             SDIS_arrestee$coeff[4] * SDIS_regression$percent.black.prison +
                                                             SDIS_arrestee$coeff[5] * SDIS_regression$percent.white.prison +
                                                             SDIS_arrestee$coeff[6] * SDIS_regression$N_arrestees.NDIS

SDIS_regression$SDIS.offender.prediction = SDIS_offender$coeff[1] + SDIS_offender$coeff[2] * SDIS_regression$census.percent.black +
                                                             SDIS_offender$coeff[3] * SDIS_regression$census.percent.white +
                                                             SDIS_offender$coeff[4] * SDIS_regression$percent.black.prison +
                                                             SDIS_offender$coeff[5] * SDIS_regression$percent.white.prison +
                                                             SDIS_offender$coeff[6] * SDIS_regression$N_offenders.NDIS

# make sure no predictions are less than 0
SDIS_regression$SDIS.offender.prediction[SDIS_regression$SDIS.offender.prediction < 0] = 0
SDIS_regression$SDIS.arrestee.prediction[SDIS_regression$SDIS.arrestee.prediction < 0] = 0

all.arrestees.SDIS <- SDIS_regression[which(!is.na(SDIS_regression$N_arrestees.SDIS)),]
all.offenders.SDIS <- SDIS_regression[which(!is.na(SDIS_regression$N_offenders.SDIS)),]

# Plot predicted vs. actual SDIS arrestees
p1 = ggplot(data = all.arrestees.SDIS) +
  geom_point(aes(x = SDIS.arrestee.prediction, y = N_arrestees.SDIS, fill = State), size = 5, col = "black", shape = 21) +
  geom_abline(intercept = 0, slope = 1, col = "grey30", linetype = "dashed", size = 1.5) +
  theme_classic() + xlab("Estimated SDIS arrestees") + ylab("SDIS arrestees") +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme(legend.position = "none")

# Plot predicted vs. actual SDIS offenders
p2 = ggplot(data = all.offenders.SDIS) +
  geom_point(aes(x = SDIS.offender.prediction, y = N_offenders.SDIS, fill = State), size = 5, col = "black", shape = 21) +
  geom_abline(intercept = 0, slope = 1, col = "grey30", linetype = "dashed", size = 1.5) +
  theme_classic() + xlab("Estimated SDIS offenders") + ylab("SDIS offenders") +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme(legend.position = "none")

# Extract legend from one of the plots
leg = get_legend(ggplot(data = all.offenders.SDIS) +
  geom_point(aes(x = SDIS.offender.prediction, y = N_offenders.SDIS, fill = State), size = 5, col = "black", shape = 21) +
  geom_abline(intercept = 0, slope = 1, col = "grey30", linetype = "dashed", size = 1.5) +
  theme_classic() + xlab("Estimated SDIS offenders") + ylab("SDIS offenders") +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme(legend.position = "bottom", axis.text.x = element_text(color = "black", size = 16, angle = 0, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(color = "black", size = 16, angle = 0, hjust = 1, vjust = 0, face = "plain"),  
        axis.title.x = element_text(color = "black", size = 16, angle = 0, hjust = .5, vjust = 0, face = "plain"),
        axis.title.y = element_text(color = "black", size = 16, angle = 90, hjust = .5, vjust = .5, face = "plain"),
        aspect.ratio = 1))

# Combine plots a and b into a grid with legend
p3 = plot_grid(p1, p2, ncol = 2)
plot_grid(NULL, p3, NULL, leg, nrow = 4, rel_heights = c(0, 1.5, 0.2, 0.5))
```

```{r final_data, warning=FALSE,message=FALSE}
Murphy = read.csv("./data/Murphy_FOIA.csv") # FOIA data from Murphy

# Reshape Murphy data to wide format
Murphy_wide = reshape(Murphy, idvar = "State", timevar = "pop", direction = "wide")
Murphy_wide = Murphy_wide[, c("State", "value.Total", "value.White", "value.Black")]

# Prepare final dataset 
final.data = merge(SDIS_regression, Murphy_wide, by = "State", all.x = TRUE)

# Calculate final estimates for Black and White populations in CODIS based on different sources
final.data = final.data[-c(which(final.data$State == "Michigan")),]
for (i in 1:nrow(final.data)) {
  print(i)
  if (!is.na(final.data$value.Total[i])) {
    final.data$final.Black[i] = final.data$value.Total[i] * (final.data$value.Black[i] / 100)
    final.data$final.White[i] = final.data$value.Total[i] * (final.data$value.White[i] / 100)
    final.data$source[i] = "Murphy"
  } else if (!is.na(final.data$N_total.SDIS[i])) {
    final.data$final.Black[i] = (final.data$N_total.SDIS[i]) * final.data$CODIS.black[i]
    final.data$final.White[i] = (final.data$N_total.SDIS[i]) * final.data$CODIS.white[i]
    final.data$source[i] = "SDIS+regression"
  } else {
    final.data$final.Black[i] = (final.data$SDIS.arrestee.prediction[i] + final.data$SDIS.offender.prediction[i]) * final.data$CODIS.black[i]
    final.data$final.White[i] = (final.data$SDIS.arrestee.prediction[i] + final.data$SDIS.offender.prediction[i]) * final.data$CODIS.white[i]
    final.data$source[i] = "Regression only"
  }
}

# Plot the final estimates for Black and White populations in CODIS
ggplot(final.data) +
  geom_point(aes(x = State, y = final.Black, fill = source, shape = "Black"), size = 2.5, col = "black") +
  geom_point(aes(x = State, y = final.White, fill = source, shape = "White"), size = 2.5, col = "black") +
  scale_fill_manual(name = "Source", labels = c("Murphy", "Regression only", "SDIS+regression"), values = c("#9A77CF", "#EC4176", "#FFA45E")) +
  scale_shape_manual(name = "Race", labels = c("Black", "White"), values = c(21, 24)) +
  theme_bw() +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  theme(axis.text.x = element_text(size = 8, angle = 90, vjust = 0.5, hjust = 1)) +
  ylab("Number of People in CODIS")

# Ensuring data can be plotted as a map
final.data.sf = st_as_sf(final.data)
final.data.sf = final.data.sf %>%
  tigris::shift_geometry()

ggplot() +
  geom_sf(data = final.data.sf$geometry, aes(fill = final.data.sf$final.Black),color = NA) + 
  geom_sf(data = final.data.sf$geometry, color = "black",lwd = 0.1,alpha = 0) +
  theme_void(base_size = 11) + 
  scale_fill_viridis(option = "magma", direction = -1)+
  labs(fill = "Number of Black people in CODIS") + 
  theme(plot.margin = unit(rep(0.5, 4), "cm")) +
  theme(legend.key.height= unit(0.2, 'cm'), legend.key.width= unit(0.2, 'cm'),
        legend.title=element_text(size=6),  legend.text=element_text(size=6)) 

ggplot() +
  geom_sf(data = final.data.sf$geometry, aes(fill = final.data.sf$final.Black/(final.data.sf$final.Black + final.data.sf$final.White)),color = NA) + 
  geom_sf(data = final.data.sf$geometry, color = "black",lwd = 0.1,alpha = 0) +
  theme_void(base_size = 11) + 
  scale_fill_viridis(option = "magma", direction = -1)+
  labs(fill = "Percent of people in CODIS that are Black") + 
  theme(plot.margin = unit(rep(0.5, 4), "cm")) +
  theme(legend.key.height= unit(0.2, 'cm'), legend.key.width= unit(0.2, 'cm'),
        legend.title=element_text(size=6),  legend.text=element_text(size=6)) 

final.data[,c("State","final.Black","final.White","source")]
write.csv(final.data, "./data/final_CODIS_data.csv")
```
